version: '3.8'

services:
  crop-recommendation:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./crop_model.pkl:/app/crop_model.pkl
    networks:
      - crop-network

networks:
  crop-network:
    driver: bridge 